import React, { useEffect, useRef, useState } from 'react'

import Link from 'next/link'
import { useRouter } from 'next/router'
import WatchlistMovers from '../../components/WatchlistMOvers'
function Gainers() {
  const [tickers, setTickers] = useState([])
  const router = useRouter()

  //   const tickers = [
  //     {
  //       symbol: 'ADBE',
  //       companyName: 'Adobe Inc.',
  //       marketCap: 179786874880,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0826,
  //       price: 384.16,
  //       lastAnnualDividend: 0,
  //       volume: 3180286,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'INTU',
  //       companyName: 'Intuit Inc.',
  //       marketCap: 113552916480,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1502,
  //       price: 402.56,
  //       lastAnnualDividend: 2.72,
  //       volume: 1927938,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: -9.64257507293416,
  //       percentChange: -2.691522728271225,
  //     },
  //     {
  //       symbol: 'TEAM',
  //       companyName: 'Atlassian Corporation Plc',
  //       marketCap: 53493362688,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0889,
  //       price: 211.03,
  //       lastAnnualDividend: 0,
  //       volume: 2030068,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'GB',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: -16.77101186386094,
  //       percentChange: -9.0071876435935,
  //     },
  //     {
  //       symbol: 'PANW',
  //       companyName: 'Palo Alto Networks, Inc.',
  //       marketCap: 51752992768,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.2886,
  //       price: 515.91,
  //       lastAnnualDividend: 0,
  //       volume: 1608145,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 16.32491973891764,
  //       percentChange: 1.758247485296387,
  //     },
  //     {
  //       symbol: 'FTNT',
  //       companyName: 'Fortinet, Inc.',
  //       marketCap: 49988169728,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.2069,
  //       price: 62.28,
  //       lastAnnualDividend: 0,
  //       volume: 6519283,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: -17.551553008189757,
  //       percentChange: -7.666976230051441,
  //     },
  //     {
  //       symbol: 'SNPS',
  //       companyName: 'Synopsys, Inc.',
  //       marketCap: 48214614016,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1987,
  //       price: 315.19,
  //       lastAnnualDividend: 0,
  //       volume: 1002008,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'CDNS',
  //       companyName: 'Cadence Design Systems, Inc.',
  //       marketCap: 43534073856,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1293,
  //       price: 157.87,
  //       lastAnnualDividend: 0,
  //       volume: 1642445,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'CRWD',
  //       companyName: 'CrowdStrike Holdings, Inc.',
  //       marketCap: 43019186176,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.4626,
  //       price: 185.37,
  //       lastAnnualDividend: 0,
  //       volume: 4652050,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'ADSK',
  //       companyName: 'Autodesk, Inc.',
  //       marketCap: 38396309504,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.4288,
  //       price: 176.72,
  //       lastAnnualDividend: 0,
  //       volume: 1836681,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'WDAY',
  //       companyName: 'Workday, Inc.',
  //       marketCap: 36967157760,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.4038,
  //       price: 145.54,
  //       lastAnnualDividend: 0,
  //       volume: 3243658,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'DDOG',
  //       companyName: 'Datadog, Inc.',
  //       marketCap: 32764917760,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2731,
  //       price: 104.01,
  //       lastAnnualDividend: 0,
  //       volume: 5653376,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //       change: Math.random() > 0.5 ? -Math.random() * 20 : Math.random() * 20,
  //       percentChange:
  //         Math.random() > 0.5 ? -Math.random() * 10 : Math.random() * 10,
  //     },
  //     {
  //       symbol: 'ZS',
  //       companyName: 'Zscaler, Inc.',
  //       marketCap: 23041388544,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1134,
  //       price: 162.42,
  //       lastAnnualDividend: 0,
  //       volume: 2496041,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'ANSS',
  //       companyName: 'ANSYS, Inc.',
  //       marketCap: 21255159808,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2831,
  //       price: 244.34,
  //       lastAnnualDividend: 0,
  //       volume: 550133,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'TTD',
  //       companyName: 'The Trade Desk, Inc.',
  //       marketCap: 20176934912,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.142,
  //       price: 43.51,
  //       lastAnnualDividend: 0,
  //       volume: 6381583,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'VRSN',
  //       companyName: 'VeriSign, Inc.',
  //       marketCap: 19262392320,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0109,
  //       price: 175.84,
  //       lastAnnualDividend: 0,
  //       volume: 817446,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //       change: 10.948535765386005,
  //       percentChange: 6.8681228318377086,
  //     },
  //     {
  //       symbol: 'NUAN',
  //       companyName: 'Nuance Communications, Inc.',
  //       marketCap: 17882421248,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0871,
  //       price: 55.99,
  //       lastAnnualDividend: 0,
  //       volume: 5693606,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'OKTA',
  //       companyName: 'Okta, Inc.',
  //       marketCap: 15837856768,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1674,
  //       price: 100.38,
  //       lastAnnualDividend: 0,
  //       volume: 3172341,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SPLK',
  //       companyName: 'Splunk Inc.',
  //       marketCap: 15523632128,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.3299,
  //       price: 96.48,
  //       lastAnnualDividend: 0,
  //       volume: 2080351,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SSNC',
  //       companyName: 'SS&C Technologies Holdings, Inc.',
  //       marketCap: 15016791040,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5558,
  //       price: 58.94,
  //       lastAnnualDividend: 1.0026,
  //       volume: 1569786,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'ZI',
  //       companyName: 'ZoomInfo Technologies Inc.',
  //       marketCap: 14598792192,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5638,
  //       price: 36.19,
  //       lastAnnualDividend: 0,
  //       volume: 4834525,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'DOCU',
  //       companyName: 'DocuSign, Inc.',
  //       marketCap: 12618466304,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0394,
  //       price: 63.11,
  //       lastAnnualDividend: 0,
  //       volume: 5477301,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PTC',
  //       companyName: 'PTC Inc.',
  //       marketCap: 12321082368,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1343,
  //       price: 105.33,
  //       lastAnnualDividend: 0,
  //       volume: 792846,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'AZPN',
  //       companyName: 'Aspen Technology, Inc.',
  //       marketCap: 11724394496,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2427,
  //       price: 188.59,
  //       lastAnnualDividend: 0,
  //       volume: 302373,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PCTY',
  //       companyName: 'Paylocity Holding Corporation',
  //       marketCap: 10311094272,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2999,
  //       price: 187.05,
  //       lastAnnualDividend: 0,
  //       volume: 311441,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PFPT',
  //       companyName: 'Proofpoint, Inc.',
  //       marketCap: 10101971968,
  //       sector: 'Technology',
  //       industry: 'Application Software',
  //       beta: 1.1992,
  //       price: 175.9,
  //       lastAnnualDividend: 0,
  //       volume: 877117,
  //       exchange: 'Nasdaq Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'FFIV',
  //       companyName: 'F5, Inc.',
  //       marketCap: 9229236224,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1815,
  //       price: 152.62,
  //       lastAnnualDividend: 0,
  //       volume: 544526,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MANH',
  //       companyName: 'Manhattan Associates, Inc.',
  //       marketCap: 7703002624,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.9011,
  //       price: 122.05,
  //       lastAnnualDividend: 0,
  //       volume: 312491,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'JCOM',
  //       companyName: 'Ziff Davis, Inc.',
  //       marketCap: 6443826688,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0328,
  //       price: 142.84,
  //       lastAnnualDividend: 0,
  //       volume: 357547,
  //       exchange: 'Nasdaq Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'CDK',
  //       companyName: 'CDK Global, Inc.',
  //       marketCap: 6390491648,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0231,
  //       price: 54.76,
  //       lastAnnualDividend: 0.6,
  //       volume: 2438803,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'TENB',
  //       companyName: 'Tenable Holdings, Inc.',
  //       marketCap: 5657375232,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.5371,
  //       price: 51.16,
  //       lastAnnualDividend: 0,
  //       volume: 1169060,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CYBR',
  //       companyName: 'CyberArk Software Ltd.',
  //       marketCap: 5521944576,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.2527,
  //       price: 135.62,
  //       lastAnnualDividend: 0,
  //       volume: 411071,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'IL',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'DSGX',
  //       companyName: 'The Descartes Systems Group Inc.',
  //       marketCap: 5415848448,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1055,
  //       price: 63.88,
  //       lastAnnualDividend: 0,
  //       volume: 196773,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MIME',
  //       companyName: 'Mimecast Limited',
  //       marketCap: 5325509120,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.346,
  //       price: 79.92,
  //       lastAnnualDividend: 0,
  //       volume: 1387382,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'GB',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'EEFT',
  //       companyName: 'Euronet Worldwide, Inc.',
  //       marketCap: 5006016000,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.3811,
  //       price: 99.03,
  //       lastAnnualDividend: 0,
  //       volume: 401446,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'COUP',
  //       companyName: 'Coupa Software Incorporated',
  //       marketCap: 4658462208,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.4442,
  //       price: 61.66,
  //       lastAnnualDividend: 0,
  //       volume: 2037603,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'LYFT',
  //       companyName: 'Lyft, Inc.',
  //       marketCap: 4301057536,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.834,
  //       price: 12.36,
  //       lastAnnualDividend: 0,
  //       volume: 13863043,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'RPD',
  //       companyName: 'Rapid7, Inc.',
  //       marketCap: 4253891328,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.3975,
  //       price: 73.01,
  //       lastAnnualDividend: 0,
  //       volume: 652855,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'NATI',
  //       companyName: 'National Instruments Corporation',
  //       marketCap: 4164774400,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0889,
  //       price: 31.75,
  //       lastAnnualDividend: 1.1,
  //       volume: 895071,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'FEYE',
  //       companyName: 'Mandiant, Inc.',
  //       marketCap: 4117945088,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.055,
  //       price: 17.27,
  //       lastAnnualDividend: 0,
  //       volume: 2963026,
  //       exchange: 'Nasdaq Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'ALTR',
  //       companyName: 'Altair Engineering Inc.',
  //       marketCap: 4117716992,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.5386,
  //       price: 51.62,
  //       lastAnnualDividend: 0,
  //       volume: 385948,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PEGA',
  //       companyName: 'Pegasystems Inc.',
  //       marketCap: 3960029952,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1357,
  //       price: 48.4,
  //       lastAnnualDividend: 0.12,
  //       volume: 606043,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CSOD',
  //       companyName: 'Cornerstone OnDemand, Inc.',
  //       marketCap: 3804642304,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2683,
  //       price: 57.49,
  //       lastAnnualDividend: 0,
  //       volume: 1328149,
  //       exchange: 'Nasdaq Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'WIX',
  //       companyName: 'Wix.com Ltd.',
  //       marketCap: 3682216448,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.5672,
  //       price: 64.08,
  //       lastAnnualDividend: 0,
  //       volume: 1301356,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'IL',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'APPN',
  //       companyName: 'Appian Corporation',
  //       marketCap: 3538799104,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.7573,
  //       price: 51.27,
  //       lastAnnualDividend: 0,
  //       volume: 639540,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'APPF',
  //       companyName: 'AppFolio, Inc.',
  //       marketCap: 3436234240,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0268,
  //       price: 98.46,
  //       lastAnnualDividend: 0,
  //       volume: 138716,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'NTNX',
  //       companyName: 'Nutanix, Inc.',
  //       marketCap: 3407025664,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.5163,
  //       price: 15.19,
  //       lastAnnualDividend: 0,
  //       volume: 2775721,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SPT',
  //       companyName: 'Sprout Social, Inc.',
  //       marketCap: 3393239040,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5098,
  //       price: 62.33,
  //       lastAnnualDividend: 0,
  //       volume: 683203,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'VRNS',
  //       companyName: 'Varonis Systems, Inc.',
  //       marketCap: 3364894720,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.2958,
  //       price: 30.71,
  //       lastAnnualDividend: 0,
  //       volume: 1194223,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'ALRM',
  //       companyName: 'Alarm.com Holdings, Inc.',
  //       marketCap: 3222116096,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2037,
  //       price: 64.33,
  //       lastAnnualDividend: 0,
  //       volume: 286543,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'ACIW',
  //       companyName: 'ACI Worldwide, Inc.',
  //       marketCap: 3117614848,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0998,
  //       price: 27.16,
  //       lastAnnualDividend: 0,
  //       volume: 706110,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'BLKB',
  //       companyName: 'Blackbaud, Inc.',
  //       marketCap: 3033104640,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0082,
  //       price: 57.29,
  //       lastAnnualDividend: 0.12,
  //       volume: 410265,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CVT',
  //       companyName: 'Cvent Holding Corp.',
  //       marketCap: 2642468608,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.9937,
  //       price: 5.49,
  //       lastAnnualDividend: 0,
  //       volume: 574663,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'EPAY',
  //       companyName: 'Bottomline Technologies, Inc.',
  //       marketCap: 2574437888,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.3578,
  //       price: 56.99,
  //       lastAnnualDividend: 0,
  //       volume: 826688,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'STNE',
  //       companyName: 'StoneCo Ltd.',
  //       marketCap: 2451400448,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.3434,
  //       price: 7.86,
  //       lastAnnualDividend: 0,
  //       volume: 8864366,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'BR',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MSTR',
  //       companyName: 'MicroStrategy Incorporated',
  //       marketCap: 2269667584,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.7427,
  //       price: 200.9,
  //       lastAnnualDividend: 0,
  //       volume: 988381,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'EVOP',
  //       companyName: 'EVO Payments, Inc.',
  //       marketCap: 2182604032,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.4811,
  //       price: 24.93,
  //       lastAnnualDividend: 0,
  //       volume: 256473,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PRGS',
  //       companyName: 'Progress Software Corporation',
  //       marketCap: 1941017344,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0662,
  //       price: 44.66,
  //       lastAnnualDividend: 0.7,
  //       volume: 337270,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'GSKY',
  //       companyName: 'GreenSky, Inc.',
  //       marketCap: 1877626112,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.4105,
  //       price: 10.2,
  //       lastAnnualDividend: 0,
  //       volume: 2077458,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'QADA',
  //       companyName: 'QAD Inc.',
  //       marketCap: 1721665152,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2655,
  //       price: 87.65,
  //       lastAnnualDividend: 0.072,
  //       volume: 236198,
  //       exchange: 'Nasdaq Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'APPS',
  //       companyName: 'Digital Turbine, Inc.',
  //       marketCap: 1624486528,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.3525,
  //       price: 16.51,
  //       lastAnnualDividend: 0,
  //       volume: 3892813,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PLUS',
  //       companyName: 'ePlus inc.',
  //       marketCap: 1389471744,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2373,
  //       price: 51.81,
  //       lastAnnualDividend: 0,
  //       volume: 131830,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SPNS',
  //       companyName: 'Sapiens International Corporation N.V.',
  //       marketCap: 1389255040,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.3607,
  //       price: 25.21,
  //       lastAnnualDividend: 0.352,
  //       volume: 211723,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'IL',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MNTV',
  //       companyName: 'Momentive Global Inc.',
  //       marketCap: 1327783296,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.41,
  //       price: 8.85,
  //       lastAnnualDividend: 0,
  //       volume: 1763195,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'AGYS',
  //       companyName: 'Agilysys, Inc.',
  //       marketCap: 1225223552,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.3394,
  //       price: 49.53,
  //       lastAnnualDividend: 0,
  //       volume: 101468,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'RPAY',
  //       companyName: 'Repay Holdings Corporation',
  //       marketCap: 1203440768,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0192,
  //       price: 13.18,
  //       lastAnnualDividend: 0,
  //       volume: 637771,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'LPSN',
  //       companyName: 'LivePerson, Inc.',
  //       marketCap: 1073564608,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.319,
  //       price: 14.42,
  //       lastAnnualDividend: 0,
  //       volume: 1085128,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'DOMO',
  //       companyName: 'Domo, Inc.',
  //       marketCap: 1048272448,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.6735,
  //       price: 31.08,
  //       lastAnnualDividend: 0,
  //       volume: 396790,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'DCBO',
  //       companyName: 'Docebo Inc.',
  //       marketCap: 1001022400,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5585,
  //       price: 28.15,
  //       lastAnnualDividend: 0,
  //       volume: 69811,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'RDWR',
  //       companyName: 'Radware Ltd.',
  //       marketCap: 965870848,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0653,
  //       price: 21.54,
  //       lastAnnualDividend: 0,
  //       volume: 220428,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'IL',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CRNC',
  //       companyName: 'Cerence Inc.',
  //       marketCap: 961017088,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.7546,
  //       price: 24.45,
  //       lastAnnualDividend: 0,
  //       volume: 503043,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'KC',
  //       companyName: 'Kingsoft Cloud Holdings Limited',
  //       marketCap: 920600064,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.503,
  //       price: 3.78,
  //       lastAnnualDividend: 0,
  //       volume: 3705856,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SCWX',
  //       companyName: 'SecureWorks Corp.',
  //       marketCap: 865567872,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.0014,
  //       price: 10.2,
  //       lastAnnualDividend: 0,
  //       volume: 103070,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'IIIV',
  //       companyName: 'i3 Verticals, Inc.',
  //       marketCap: 858476288,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.4123,
  //       price: 26.48,
  //       lastAnnualDividend: 0,
  //       volume: 153000,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PDFS',
  //       companyName: 'PDF Solutions, Inc.',
  //       marketCap: 804171264,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.4238,
  //       price: 21.76,
  //       lastAnnualDividend: 0,
  //       volume: 131233,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'RIOT',
  //       companyName: 'Riot Blockchain, Inc.',
  //       marketCap: 659144768,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 4.3766,
  //       price: 4.87,
  //       lastAnnualDividend: 0,
  //       volume: 12261686,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'EBIX',
  //       companyName: 'Ebix, Inc.',
  //       marketCap: 555050176,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.4764,
  //       price: 17.96,
  //       lastAnnualDividend: 0.3,
  //       volume: 535218,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CISO',
  //       companyName: 'Cerberus Cyber Sentinel Corporation',
  //       marketCap: 528749184,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.083,
  //       price: 4.24,
  //       lastAnnualDividend: 0,
  //       volume: 584608,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'ZIXI',
  //       companyName: 'Zix Corporation',
  //       marketCap: 481867360,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1896,
  //       price: 8.485,
  //       lastAnnualDividend: 0,
  //       volume: 1204418,
  //       exchange: 'Nasdaq Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'SSTI',
  //       companyName: 'ShotSpotter, Inc.',
  //       marketCap: 367283392,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2377,
  //       price: 30.25,
  //       lastAnnualDividend: 0,
  //       volume: 37933,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'LSAK',
  //       companyName: 'Lesaka Technologies, Inc.',
  //       marketCap: 313646048,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1639,
  //       price: 5.3,
  //       lastAnnualDividend: 0,
  //       volume: 64573,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'ZA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SPRT',
  //       companyName: 'Support.com, Inc.',
  //       marketCap: 284440192,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0901,
  //       price: 11.8,
  //       lastAnnualDividend: 1,
  //       volume: 20267331,
  //       exchange: 'Nasdaq Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'UEPS',
  //       companyName: 'Lesaka Technologies, Inc.',
  //       marketCap: 270161984,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.2321,
  //       price: 4.74,
  //       lastAnnualDividend: 0,
  //       volume: 72324,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'ZA',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'BNFT',
  //       companyName: 'Benefitfocus, Inc.',
  //       marketCap: 269867520,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.6579,
  //       price: 7.95,
  //       lastAnnualDividend: 0,
  //       volume: 130588,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'VERI',
  //       companyName: 'Veritone, Inc.',
  //       marketCap: 257164128,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 3.191,
  //       price: 7.13,
  //       lastAnnualDividend: 0,
  //       volume: 494030,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'RDVT',
  //       companyName: 'Red Violet, Inc.',
  //       marketCap: 256262752,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0183,
  //       price: 18.95,
  //       lastAnnualDividend: 0,
  //       volume: 70285,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PRCH',
  //       companyName: 'Porch Group, Inc.',
  //       marketCap: 239911296,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.3064,
  //       price: 2.42,
  //       lastAnnualDividend: 0,
  //       volume: 2420108,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SHSP',
  //       companyName: 'SharpSpring, Inc.',
  //       marketCap: 220362576,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.8402,
  //       price: 17.1,
  //       lastAnnualDividend: 0,
  //       volume: 194459,
  //       exchange: 'Nasdaq Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'CLSK',
  //       companyName: 'CleanSpark, Inc.',
  //       marketCap: 184566736,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 3.6298,
  //       price: 4.47,
  //       lastAnnualDividend: 0.12,
  //       volume: 1733955,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'IMMR',
  //       companyName: 'Immersion Corporation',
  //       marketCap: 181852272,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.735,
  //       price: 5.41,
  //       lastAnnualDividend: 0,
  //       volume: 332996,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PHUN',
  //       companyName: 'Phunware, Inc.',
  //       marketCap: 135012016,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 14.9353,
  //       price: 1.38,
  //       lastAnnualDividend: 0,
  //       volume: 2695108,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'JG',
  //       companyName: 'Aurora Mobile Limited',
  //       marketCap: 113931840,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1534,
  //       price: 0.96,
  //       lastAnnualDividend: 0,
  //       volume: 242068,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SNCR',
  //       companyName: 'Synchronoss Technologies, Inc.',
  //       marketCap: 100663480,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.1475,
  //       price: 1.14,
  //       lastAnnualDividend: 0,
  //       volume: 219565,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'REKR',
  //       companyName: 'Rekor Systems, Inc.',
  //       marketCap: 86283232,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.107,
  //       price: 1.73,
  //       lastAnnualDividend: 0,
  //       volume: 1308193,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'PCYG',
  //       companyName: 'Park City Group, Inc.',
  //       marketCap: 83683352,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0481,
  //       price: 4.5,
  //       lastAnnualDividend: 0,
  //       volume: 45368,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'INTZ',
  //       companyName: 'Intrusion Inc.',
  //       marketCap: 80950800,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.2495,
  //       price: 4.19,
  //       lastAnnualDividend: 0,
  //       volume: 53653,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'AUID',
  //       companyName: 'Ipsidy Inc.',
  //       marketCap: 72043704,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.5611,
  //       price: 2.92,
  //       lastAnnualDividend: 0,
  //       volume: 63071,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MOGO',
  //       companyName: 'Mogo Inc.',
  //       marketCap: 70423536,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 4.0546,
  //       price: 0.91,
  //       lastAnnualDividend: 0,
  //       volume: 426745,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'NETE',
  //       companyName: 'Net Element, Inc.',
  //       marketCap: 68189216,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.9855,
  //       price: 13.09,
  //       lastAnnualDividend: 0,
  //       volume: 582471,
  //       exchange: 'Nasdaq Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'AEYE',
  //       companyName: 'AudioEye, Inc.',
  //       marketCap: 67676688,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.1847,
  //       price: 5.89,
  //       lastAnnualDividend: 0,
  //       volume: 57461,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CIH',
  //       companyName: 'China Index Holdings Limited',
  //       marketCap: 64093524,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.4334,
  //       price: 0.7088,
  //       lastAnnualDividend: 0,
  //       volume: 200230,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SURG',
  //       companyName: 'SurgePays, Inc.',
  //       marketCap: 58905664,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5937,
  //       price: 4.81,
  //       lastAnnualDividend: 0,
  //       volume: 90598,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MCLD',
  //       companyName: 'mCloud Technologies Corp.',
  //       marketCap: 49454000,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1575,
  //       price: 3.01,
  //       lastAnnualDividend: 0,
  //       volume: 19370,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MARK',
  //       companyName: 'Remark Holdings, Inc.',
  //       marketCap: 48372680,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 3.4297,
  //       price: 0.46,
  //       lastAnnualDividend: 0,
  //       volume: 1542221,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'OMQS',
  //       companyName: 'OMNIQ Corp.',
  //       marketCap: 45742296,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.1528,
  //       price: 6.05,
  //       lastAnnualDividend: 0,
  //       volume: 17650,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'XELA',
  //       companyName: 'Exela Technologies, Inc.',
  //       marketCap: 44903748,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.8135,
  //       price: 0.1016,
  //       lastAnnualDividend: 0,
  //       volume: 69876143,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'ANY',
  //       companyName: 'Sphere 3D Corp.',
  //       marketCap: 44071152,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.2346,
  //       price: 0.6831,
  //       lastAnnualDividend: 0,
  //       volume: 1559008,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'IDN',
  //       companyName: 'Intellicheck, Inc.',
  //       marketCap: 41698500,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.7972,
  //       price: 2.21,
  //       lastAnnualDividend: 0,
  //       volume: 80773,
  //       exchange: 'NASDAQ Global Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'GBOX',
  //       companyName: 'GreenBox POS',
  //       marketCap: 34029360,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 4.9301,
  //       price: 0.8216,
  //       lastAnnualDividend: 0,
  //       volume: 579871,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'BRQS',
  //       companyName: 'Borqs Technologies, Inc.',
  //       marketCap: 31519178,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2823,
  //       price: 1.69,
  //       lastAnnualDividend: 0,
  //       volume: 3482833,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'DGHI',
  //       companyName: 'Digihost Technology Inc.',
  //       marketCap: 29770648,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 5.8699,
  //       price: 1.0753,
  //       lastAnnualDividend: 0,
  //       volume: 68745,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CA',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'INPX',
  //       companyName: 'Inpixon',
  //       marketCap: 29732818,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.8339,
  //       price: 0.195,
  //       lastAnnualDividend: 0,
  //       volume: 3748653,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'FTFT',
  //       companyName: 'Future FinTech Group Inc.',
  //       marketCap: 29428182,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.2132,
  //       price: 0.42,
  //       lastAnnualDividend: 0,
  //       volume: 494275,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SEAC',
  //       companyName: 'SeaChange International, Inc.',
  //       marketCap: 27450798,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.0331,
  //       price: 0.557,
  //       lastAnnualDividend: 0,
  //       volume: 1772171,
  //       exchange: 'NASDAQ Global Select',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'BSQR',
  //       companyName: 'BSQUARE Corporation',
  //       marketCap: 26170752,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5309,
  //       price: 1.28,
  //       lastAnnualDividend: 0,
  //       volume: 60628,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'GVP',
  //       companyName: 'GSE Systems, Inc.',
  //       marketCap: 24587544,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.4682,
  //       price: 1.1701,
  //       lastAnnualDividend: 0,
  //       volume: 23773,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'NXPL',
  //       companyName: 'NextPlat Corp',
  //       marketCap: 19894668,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.0988,
  //       price: 2.1408,
  //       lastAnnualDividend: 0,
  //       volume: 23693,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'EVOL',
  //       companyName: 'Symbolic Logic, Inc.',
  //       marketCap: 18007706,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.5177,
  //       price: 1.4601,
  //       lastAnnualDividend: 0,
  //       volume: 118260,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'AHI',
  //       companyName: 'Advanced Human Imaging Limited',
  //       marketCap: 17019334,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.4145,
  //       price: 0.6028,
  //       lastAnnualDividend: 0,
  //       volume: 69956,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'AU',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'SSNT',
  //       companyName: 'SilverSun Technologies, Inc.',
  //       marketCap: 15459902,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.3639,
  //       price: 3.01,
  //       lastAnnualDividend: 0.6,
  //       volume: 46796,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'QUMU',
  //       companyName: 'Qumu Corporation',
  //       marketCap: 14254186,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 1.6642,
  //       price: 0.7988,
  //       lastAnnualDividend: 0,
  //       volume: 57015,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'BLIN',
  //       companyName: 'Bridgeline Digital, Inc.',
  //       marketCap: 13282880,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.7827,
  //       price: 1.3,
  //       lastAnnualDividend: 0,
  //       volume: 70780,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CREX',
  //       companyName: 'Creative Realities, Inc.',
  //       marketCap: 12928756,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 3.4428,
  //       price: 0.595,
  //       lastAnnualDividend: 0,
  //       volume: 167383,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'HUSN',
  //       companyName: 'Hudson Capital Inc.',
  //       marketCap: 11820732,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.2688,
  //       price: 1.68,
  //       lastAnnualDividend: 0,
  //       volume: 1776070,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: false,
  //     },
  //     {
  //       symbol: 'APCX',
  //       companyName: 'AppTech Payments Corp.',
  //       marketCap: 9566552,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 1.7263,
  //       price: 0.5902,
  //       lastAnnualDividend: 0,
  //       volume: 163830,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'OBLG',
  //       companyName: 'Oblong, Inc.',
  //       marketCap: 9090720,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.5747,
  //       price: 0.295,
  //       lastAnnualDividend: 0,
  //       volume: 214808,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CETX',
  //       companyName: 'Cemtrex, Inc.',
  //       marketCap: 7485040,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.3562,
  //       price: 0.285,
  //       lastAnnualDividend: 0,
  //       volume: 467751,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MTC',
  //       companyName: 'MMTec, Inc.',
  //       marketCap: 7211963,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 3.5282,
  //       price: 0.2299,
  //       lastAnnualDividend: 0,
  //       volume: 277108,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'CN',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'MYSZ',
  //       companyName: 'My Size, Inc.',
  //       marketCap: 6014467,
  //       sector: 'Technology',
  //       industry: 'Software—Application',
  //       beta: 2.8087,
  //       price: 0.237,
  //       lastAnnualDividend: 0,
  //       volume: 1027405,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'IL',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //     {
  //       symbol: 'CETXP',
  //       companyName: 'Cemtrex, Inc.',
  //       marketCap: 4081942,
  //       sector: 'Technology',
  //       industry: 'Software—Infrastructure',
  //       beta: 2.3562,
  //       price: 0.895,
  //       lastAnnualDividend: 0,
  //       volume: 61923,
  //       exchange: 'NASDAQ Capital Market',
  //       exchangeShortName: 'NASDAQ',
  //       country: 'US',
  //       isEtf: false,
  //       isActivelyTrading: true,
  //     },
  //   ]

  //   const watchlist = tickers.slice(0, 5)
  useEffect(() => {
    const url =
      'https://financialmodelingprep.com/api/v3/stock_market/actives?apikey=28d6ee65329243c33f2324e5651df196'

    const fetchData = async () => {
      try {
        const response = await fetch(url)
        const json = await response.json()
        setTickers(json)
      } catch (error) {
        console.log('error', error)
      }
    }

    fetchData()
  }, [])
  console.log(tickers)
  const goToPage = (url) => {
    ç
    router.push({
      pathname: `/finance/${url}`,
    })
  }
  return (
    <div className="flex w-[550px] flex-col xl:ml-0  ">
      <p className="  mb-3 text-lg  font-light text-gray-900 ">
        Top movers in your lists
      </p>
      {tickers.map((ticker) => (
        // <Link href={`/finance/${ticker.symbol}:${ticker.exchangeShortName}`}>
        <div
          onClick={() => {
            goToPage(ticker.symbol)
          }}
          key={ticker.id}
          className=" flex cursor-pointer flex-col transition duration-200 ease-in-out  hover:bg-gray-50 "
        >
          <WatchlistMovers
            ticker={ticker.symbol}
            price={ticker.price}
            change={ticker.change?.toFixed(2)}
            desc={ticker.companyName}
            percentChange={ticker.percentChange?.toFixed(2)}
          />
        </div>
        // </Link>
      ))}
    </div>
  )
}

export default Gainers
